#DOCKERFILE FOR TESTS
FROM gcc:latest

RUN apt-get update && apt-get install -y cmake

COPY . /usr/src/project
WORKDIR /usr/src/project

ENV MAIN_DIR="."
ENV SOURCE_DIR="./src"
ENV TESTS_DIR="./tests"
ENV FILES_DIR="./files"

RUN mkdir build
WORKDIR /usr/src/project/build

RUN cmake .. && make 

#run tests
WORKDIR /usr/src/project
CMD ["./build/tests/runTests"]